
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP 
 */
public class homePage extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form homePage
     */
    Voice voice;
    String txt;
    Connection con;
    public homePage(Connection con) {
            initComponents();
            this.con=con;
        Toolkit tk= Toolkit.getDefaultToolkit();
        int xsize=(int)tk.getScreenSize().getWidth();
        int ysize=(int)tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
   
        
        VoiceManager vm = VoiceManager.getInstance();
        voice = vm.getVoice("kevin16");

        voice.allocate();
        
         
       
    }

       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home_panel = new javax.swing.JPanel();
        home_txt = new javax.swing.JTextField();
        home_button = new javax.swing.JButton();
        h_panel = new javax.swing.JPanel();
        ImageIcon icon=new ImageIcon(getClass().getResource("river.jpg"));
        Image image= icon.getImage();
        home_dk_pane = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g) {
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        home_txt.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        home_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_txtActionPerformed(evt);
            }
        });
        home_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                home_txtKeyPressed(evt);
            }
        });

        home_button.setBackground(new java.awt.Color(102, 255, 51));
        home_button.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        home_button.setText("GO");
        home_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home_buttonActionPerformed(evt);
            }
        });

        h_panel.setBackground(new java.awt.Color(255, 255, 0));
        h_panel.setLayout(new javax.swing.OverlayLayout(h_panel));

        javax.swing.GroupLayout home_dk_paneLayout = new javax.swing.GroupLayout(home_dk_pane);
        home_dk_pane.setLayout(home_dk_paneLayout);
        home_dk_paneLayout.setHorizontalGroup(
            home_dk_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        home_dk_paneLayout.setVerticalGroup(
            home_dk_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );

        h_panel.add(home_dk_pane);

        javax.swing.GroupLayout home_panelLayout = new javax.swing.GroupLayout(home_panel);
        home_panel.setLayout(home_panelLayout);
        home_panelLayout.setHorizontalGroup(
            home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_panelLayout.createSequentialGroup()
                .addComponent(home_txt, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(home_button, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(h_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        home_panelLayout.setVerticalGroup(
            home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_panelLayout.createSequentialGroup()
                .addGroup(home_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(h_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_home_txtKeyPressed

    }//GEN-LAST:event_home_txtKeyPressed

    private void home_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_txtActionPerformed
        
    }//GEN-LAST:event_home_txtActionPerformed

    private void home_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home_buttonActionPerformed
       try{
          txt=home_txt.getText();
          Date d = new Date();
                SimpleDateFormat k=new SimpleDateFormat("dd/MMM/yyyy hh:mm:ss a E z");
                String date=k.format(d);
          String q = "insert into history values(?,?)";
            PreparedStatement y = con.prepareStatement(q);
            y.setString(1,"https://www."+ txt);
            y.setString(2, date);
            int x = y.executeUpdate();
            
      }
     catch(Exception e)
     {
          JOptionPane.showMessageDialog(this, "Sorry Error occures" + e.getMessage());
     }
        
       JFXPanel fxpanel=new JFXPanel();
       
        h_panel.removeAll();
       
        h_panel.add(fxpanel);
         
        Thread t=new Thread(this);
                t.start();
         Platform.runLater(new Runnable() {
            @Override
            public void run() {
                
                
                 WebEngine engine;
                WebView wv=new WebView();
                engine=wv.getEngine();
                fxpanel.setScene(new Scene (wv));
                engine.load("https://www."+txt);
             
                
            }

            
        });
         
        h_panel.repaint();
        
        h_panel.revalidate();
    }//GEN-LAST:event_home_buttonActionPerformed

    public void run()
    {
        try {
          
            voice.speak(txt+"is searching");

        } catch (Exception ex) {
             JOptionPane.showMessageDialog(this, "Sorry Error occures" + ex.getMessage());
           
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(homePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new homePage().setVisible(true);
//                
//                
//               
//            }
//        });
//    }
//
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel h_panel;
    public javax.swing.JButton home_button;
    public javax.swing.JDesktopPane home_dk_pane;
    public javax.swing.JPanel home_panel;
    public javax.swing.JTextField home_txt;
    // End of variables declaration//GEN-END:variables
}
